[package]
name = "rsntp"
version = "0.0.1"
authors = ["Miroslav Lichvar <mlichvar0@gmail.com>"]
description = "Multi-threaded NTP server"
license = "GPLv2+"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
getopts = "0.2.21"
hyper = { version = "1.0", features = ["full"] }
http-body-util = "0.1"
moka = { version = "0.12", features = ["future"] }
net2 = "0.2.39"
privdrop = "0.5.4"
prometheus-client = "0.22"
rand = "0.8"
tokio = { version = "1.0", features = ["full"] }
